### ISSUE TITLE
[Bug] Which version of transformers should I use

### ISSUE THREAD

**Issue by Kayzwer** [coqui-ai/TTS#4420]
### Describe the bug

Which version of transformers should I use

### To Reproduce

```
import torch
from TTS.api import TTS


device = "cuda"

tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)
wav = tts.tts(text="Hello world!", speaker_wav="./audio.wav", language="en")
```

### Logs

```shell
ImportError: cannot import name 'BeamSearchScorer' from 'transformers' (/home/kayzwer/Envs/tts_env/lib/python3.11/site-packages/transformers/__init__.py)
```

### Environment

```shell
- TTS Version: 0.22.0
- Python Version: 3.11.15
- OS: EndeaevourOS
- CUDA Version: 13.2
- RTX 4050 Mobile
- torch installed with pip
```

**Comment by eginhard** [comment]
First you need to install the latest version (0.27.5) of our fork instead
of the original package:
https://coqui-tts.readthedocs.io/en/latest/faq.html#what-is-the-coqui-fork-about-and-how-to-install-it

The fork currently works with transformers up to 5.0
